name: PR CI/CD
on:
  # push:
  #   branches:
  #     - master
  pull_request:
    branches:
      - master

jobs:
  cd:
    env:
      DOCKER_TMP_NAME: mdlint
    runs-on: ubuntu-latest
    # needs: ci
    steps:
      - uses: actions/checkout@v1
      - name: Docker login
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build
        run: docker build -t $DOCKER_TMP_NAME .
      - name: Tags
        run: |
          docker tag $DOCKER_TMP_NAME ${{ github.repository }}:${{ github.sha }}
      - name: Push
        run: |
          docker push ${{ github.repository }}:${{ github.sha }}
